<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block AHT\SaleAgent\Block\Account\Dashboard\SaleAgentCommission */
?>
<div class="block block-dashboard-product-commission">
    <?php
    $_saleAgents = $block->getAgent();
    $count = count($_saleAgents);
    ?>
    <div class="block-title agent">
        <strong><?= $block->escapeHtml(__('Commission Product')) ?></strong>
        <?php if ($count > 0) : ?>
            <a class="action view" href="<?= $block->escapeUrl($block->getUrl('saleagent/order/index/')) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
        <?= $block->getChildHtml() ?>
        <?php if ($_saleAgents && $count) : ?>
            <div class="table-wrapper commission-recent">
                <table class="data table table-commission-items recent" id="product-commission-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Sale Agent')) ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="col product-name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                            <th scope="col" class="col product-sku"><?= $block->escapeHtml(__('Product SKU')) ?></th>
                            <th scope="col" class="col product-price"><?= $block->escapeHtml(__('Product Price')) ?></th>
                            <th scope="col" class="col product-qty"><?= $block->escapeHtml(__('Product Qty')) ?></th>
                            <th scope="col" class="col commission-value"><?= $block->escapeHtml(__('Total Assigned')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_saleAgents as $_saleAgent) : ?>
                            <?php $_product = $block->getProduct($_saleAgent->getOrderItemSku()); ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col product-name"><?= $block->escapeHtml($_saleAgent->getName()) ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Product SKU')) ?>" class="col product-sku"><?= $_saleAgent->getSku() ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Product Price')) ?>" class="col product-price"><?= $block->getFormatedPrice($_saleAgent->getOrderItemPrice()) ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Product Qty')) ?>" class="col product-qty"><?= $block->convertQty($_saleAgent->getQty()) ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Total Assigned')) ?>" class="col Total Assigned"><?= $block->getFormatedPrice($_saleAgent->getTotal()) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no product commission.')) ?></span></div>
        <?php endif; ?>
    </div>
</div>